name: jxtsaminfra-go-terraform-provider-test
description: Test workflow for the jxtsaminfra Go Terraform provider.
on:
  pull_request:
    branches:
      - master
      - main

defaults:
  runs:
    on: ubuntu-latest
    timeout-minutes: 60
    working-directory: jxtsaminfra_ec2_change_instance_type
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        terraform:
          - '1.0.*'
          - '1.1.*'
          - '1.2.*'
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - uses: actions/checkout@v3
      - run: go mod download
      - run: go mod tidy
      - run: go build -v .
      - name: Run linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest